language: node_js
node_js:
    - '0.10'
before_script:
    - 'npm install -g bower grunt-cli'
    - 'bower install'
script:
    - grunt travis
    # - cat coverage/PhantomJS*/lcov.info | node_modules/coveralls/bin/coveralls.js || true
